# Generated by Django 4.2.3 on 2023-09-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'prioritize']},
        ),
        migrations.AddField(
            model_name='task',
            name='prioritize',
            field=models.BooleanField(default=False),
        ),
    ]
